### ISSUE TITLE
Question about running CSI drivers

### ISSUE THREAD

**Issue by michaelmosher** [hashicorp/nomad-driver-podman#161]
Hello,

I'm hoping to run the [EFS CSI driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver) using Podman. I believe Podman supports privileged containers, and I presume the implementation will be compatible with CSI drivers, but I don't see how to do that with this plugin. I would expect to need to set `allow_privileged = true` in the plugin configuration (similar to the [Docker plugin](https://www.nomadproject.io/docs/drivers/docker#allow_privileged)), and I would expect to need to set `privileged = true` in the task configuration (similar to [docker tasks](https://www.nomadproject.io/docs/drivers/docker#privileged)). 

Is that currently possible?

**Comment by tgross** [comment]
Hi @michaelmosher! The podman driver doesn't have a coarse-grained `privileged` option. You'll need to set the [`cap_add`](https://www.nomadproject.io/plugins/drivers/podman#cap_add) to include `SYSADMIN` (for `CAP_SYSADMIN` which is required for [`mount(2)`](https://man7.org/linux/man-pages/man2/mount.2.html)). 

I'm going to admit I'm not 100% sure how this interacts with rootless containers, but my suspicion is that it doesn't work at all. That's not a security problem _per se_ because you already need to give the container `CAP_SYSADMIN` which lets it escalate to arbitrary privileges as it is. But something to look out for.

**Comment by michaelmosher** [comment]
Thanks for the fast response! That sounds pretty simple – I'll give it a try.  :)
