### ISSUE TITLE
CNI Support?

### ISSUE THREAD

**Issue by kbknapp** [hashicorp/nomad-driver-podman#173]
At my work we're trying to use this plugin to run tasks via Podman. Using just bare Podman we use an in-house CNI plugin that connects the container namespace to our network stack. However, this plugin doesn't seem to have support for calling CNI plugins. Or perhaps I'm just holding it wrong?

The CNI plugin is actually pretty simple, so just using bare podman this is all that's required (assuming our CNI plugin is properly installed of course):

```console
$ CNI_ARGS=... podman run --net=mynet my-container-image

# Alternatively we can omit the CNI_ARGS env variable and specify it in 
# our CNI configuration file...but that's less preferred
# In that case, the podman invocation becomes even more "standard"
$ podman run --net=mynet my-container-image
```

So essentially, to be able to use this plugin in our setup, we'd just need this plugin's `network_mode` to allow passing through raw values to `--net=...`. And a "complete" support would allow us to provide the `CNI_ARGS` environment variable to Podman too.

Is this currently possible, and/or implementable? Thank you for the work on this plugin! 😄

**Comment by antleyva** [comment]
Ditto, we need this solution for our current deployment

**Comment by shoenig** [comment]
CNI support is deprecated in Podman v4 and is being removed in v5. 

Regardless, you should be able to configure your CNI plugin using [Nomad's CNI support](https://developer.hashicorp.com/nomad/docs/networking/cni), rather than configuring it through podman directly. If that doesn't work, definitely file an issue - probably against the Nomad issue tracker.
