### ISSUE TITLE
Default `image_pull_timeout` exceeds `client_http_timeout`

### ISSUE THREAD

**Issue by courtland** [hashicorp/nomad-driver-podman#207]
The default `image_pull_timeout` of 5 minutes exceeds the default `client_http_timeout` of 60 seconds. The **actual** image pull timeout is effectively 60s by default.

I found it a bit confusing that these defaults contradict the docs: _image_pull_timeout ... cannot be longer than the client_http_timeout_. While debugging an issue where my image pulls were timing out on my slow Internet connection, I realized the client timeout needed to be bumped to match the pull timeout.

I'm trying to understand the reasoning for these defaults? Is it to establish a reasonable image timeout in the event someone raises the client timeout? I would propose that the client timeout is raised to match the image timeout. I'm happy to open a PR if this is makes sense? Thank you!

**Comment by lgfa29** [comment]
Hi @courtland 👋 

Thanks for the report. I think this was unintended consequence of different defaults being set without noticing that one impacts the other.

While increasing the default timeout would work out-of-the-box the experience of having to manage both values is not great, so I opened #218 to use a separate HTTP client for image pull operations. I think this provides a better result since now these two values are independent from each other.

**Comment by courtland** [comment]
Hi @lgfa29 👋 

I figured as much, thanks for opening a PR to address it.  I think this will be save to close after it's merged.
