### ISSUE TITLE
Can I just use the binaries? What do you recommend?

### ISSUE THREAD

**Issue by ramonck** [hashicorp/nomad-driver-podman#76]
Hi,

I was wondering if I could just use the nomad and nomad-drive-podman binaries, what do you recommend in terms of utilization and setup? I saw the README and it seems that you guys are looking for to the build I was thinking about not doing the build but rather just use the binaries.

Will the binary work in Ubuntu, Fedora?

Seems that the Nomad setups are more Fedora oriented, I'm fine with the Fedora is just that I wanted to understand if I could just used the binaries and how should I use them and where is best.

**Comment by towe75** [comment]
Hi @ramonck ,

yes, the binaries will work on both ubuntu and fedora.

Follow the podman docs to install podman 2.x for the distro of your choice. Be sure to enable the http api socket.
For nomad and the plugin: download the binaries and configure nomad. The "-dev" mode should help you get startet quickly. Ensure to set plugin_dir correctly so that nomad can find the plugin.

**Comment by ramonck** [comment]
sounds good thanks.
