### ISSUE TITLE
Possible discrepancy between README and code regarding default network mode for rootless containers

### ISSUE THREAD

**Issue by lnde** [hashicorp/nomad-driver-podman#93]
Hi,

The README says that `slirp4netns` is the default network mode for rootless containers but that doesn't seem to be the case when testing and looking at the code. It seems the default is `bridge` even when running rootless containers. I stumbled into this when playing around with Nomad for the very first time so there's plenty of room for mistakes on my part.

Anyway my solution was to simply specify `network_mode = "slirp4netns"` in the config-section. This was tested on v0.2.0 release and 0502b79 (with bf21e157 reverted as it breaks with Podman 2.2.1), and I'd be happy to help test any patches.

Nomad v1.0.4
Podman 2.2.1

Documentation:
https://github.com/hashicorp/nomad-driver-podman/blame/main/README.md#L240
Code:
https://github.com/hashicorp/nomad-driver-podman/blob/0502b790bcafe0b87ea77290559b0c259586895c/driver.go#L433

Thanks,
Andreas

**Comment by silvercrown07** [comment]
stumbled upon this issue as well, for me the setup is:
Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)
podman version 3.0.1 (c640670e85c4aaaff92741691d6a854a90229d8d)
also used the same workaround, at first thought was due to https://github.com/hashicorp/nomad-driver-podman/issues/92 but seems the `rootless` attribute is only used for display purposes in nomad ui 😆

**Comment by towe75** [comment]
We can surely change the default mode to slirp4nets once the rootless check is fixed.
Thank you for the report!
